### ISSUE TITLE
Order of `PresetTimeCallback` and an `ODEFunction` is non-intuitive

### ISSUE THREAD

**Issue by Vilin97** [SciML/DiffEqCallbacks.jl#172]
I am trying to understand the order of evaluation of a callback and an ode function. It seems somewhat cryptic. The callback seems to go before the ode function at first but then switches to going after, in effect skipping one step in-between.
```
using OrdinaryDiffEq, DiffEqCallbacks
tspan = (0.0, 2.0)
dt = 1.
ts = collect(tspan[1]:dt:tspan[2])
g!(integrator) = (u_modified!(integrator, false); println("$(integrator.t) g "))
f!(du,u,p,t) = (du .= u; println("$t f "))
cb = PresetTimeCallback(ts, g!, save_positions=(false, false))
solve(ODEProblem(f!, [1.0], tspan), Euler(), dt=dt, callback=cb)
```
Output:
```
0.0 g 
0.0 f 
1.0 f
1.0 g
2.0 f
2.0 g
```

**Comment by ChrisRackauckas** [comment]
Described on Slack, this is because `tspan[1]` is in the time choice and thus `initialize!` is setup so that it calls the `affect!` at time 0. This is a special behavior to ensure correctness, given that the user in this instance told us of the special case that there should be an event applied before the start of the simulation.
